FROM gcc:10.1.0

WORKDIR /apps

# Installing SuperHirn

RUN apt-get update && \
    apt-get -y install git && \
    git clone https://github.com/mergipe/SuperHirn.git && \
    cd SuperHirn/SuperHirnv03/make/ && \
    make

ENTRYPOINT ["bash"]